# Default configuration for Spatial Graph Contrastive Learning

# Data paths
data_dir: "../data"
output_dir: "../output"
figure_dir: "../figures"
model_dir: "../models"

# Dataset configuration
spatial_dataset_path: "MERFISH/HC_2sample_combined_sampled.h5ad"
bulk_dataset_path: "TCGA/Processed/TCGA_LIHC.h5ad"
spatial_dataset: "HC2combined_sampled_hop2"
bulk_dataset: "TCGA_LIHC"
spatial_color_by: "sub_cell_type"

# Query configuration
query_column: "sample_type.samples"
query_filter: ""
query_k: 200
distance_metric: "cosine"

# Training parameters
seed: 42
train_ratio: 0.8
batch_size: 128
num_workers: 4
device: "cuda"
log_every_n_steps: 5
wandb_project: "SpatialGCL"
run_name: "GAT"

# Spatial graph parameters
n_neighbors: 20
hops: 2

# Graph Contrastive Learning model parameters
gcl_latent_dim: 32
gcl_hidden_dim: 128
gcl_recon_weight: 0.8
gcl_margin: 1.0
gcl_max_epochs: 10
gcl_conv_layer: 'GAT'

# Bulk encoder model parameters
bulk_latent_dim: 32
bulk_hidden_dims: [256, 128]
bulk_max_epochs: 20

